OVMF: add command to build new firmware
Signed-off-by: Yaniv Levinsky <yaniv.levinsky@compulab.co.il>

diff --git a/efiappbnc b/efiappbnc
--- a/efiappbnc
+++ b/efiappbnc
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 MAJOR_VERSION=0
-MINOR_VERSION=1
+MINOR_VERSION=2
 PATCH_VERSION=0
 
 usage_exit()
@@ -10,6 +10,7 @@ usage_exit()
 efiappbnc $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION
 Usage: efiappbnc [<options>] [<application_name>]
        efiappbnc configure
+       efiappbnc ovmf
 
 DESCRIPTION
 	The script builds EFI applications using the EDK2 environment and copys
@@ -18,6 +19,10 @@ DESCRIPTION
 CONFIGURE
 	The configure command allows you to edit configuration variables. The
 	values that you set here will be used on each invoke of the script.
+
+OVMF
+	The ovmf command builds the OvmfX64 package and replaces the firmware
+	files of the qemu session.
 
 APPLICATIONS PROFILES
 	The script supports saving and loading of application profiles. Profiles
@@ -326,12 +331,45 @@ reset_qemu()
 	virsh reset $(virsh list --name)
 }
 
+build_ovmf()
+{
+	load_configs
+
+	PLATFORM_NAME=OvmfX64
+	PACKAGE_NAME=OvmfPkg
+	PLATFORM_FILE=OvmfPkgX64.dsc
+	FAST="true"
+	edk2_build
+
+	announce "Copy OVMF firmware"
+	check_config OVMF_PATH
+	cd ${OVMF_PATH}
+	cp ${EDK2_PATH}/Build/${PLATFORM_NAME}/DEBUG_GCC5/FV/OVMF_CODE.fd OVMF_CODE.fd
+	[ $? -eq 0 ] || abort "Copy OVMF_CODE.fd failed"
+	cp ${EDK2_PATH}/Build/${PLATFORM_NAME}/DEBUG_GCC5/FV/OVMF_VARS.fd OVMF_VARS.fd
+	[ $? -eq 0 ] || abort "Copy OVMF_VARS.fd failed"
+	cd ${SCRIPT_START_DIR}
+
+	announce "Destroying OVMF session"
+	local OVMF_NAME=$(virsh list --name)
+	virsh destroy ${OVMF_NAME}
+
+	announce "Restarting OVMF session"
+	virsh start ${OVMF_NAME}
+}
+
 parse_cmdline_input()
 {
 	while true; do
 		case "$1" in
 		configure)
 			edit_configs
+			echo "Done!"
+			exit 0
+			shift
+			;;
+		ovmf)
+			build_ovmf
 			echo "Done!"
 			exit 0
 			shift
